# Generated by Django 3.0.5 on 2020-04-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200420_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='length',
            new_name='images',
        ),
    ]
